const express = require("express");
const router = express.Router();

router.get("/", (req, res) => {
    res.status(200).json({
        id1: {
            name: "Pachirisu",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type1Color: "blue",
            type2: "Poison",
            type2Color: "green",
            imageUrl: "./pokemonPictures/Pachirisu.png",
            imageUrlModal: "./pokemonPictures/Pachirisu.png",
            background: "blueGradient",
        },
        id2: {
            name: "Pyroar",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Pyroar.png",
            imageUrlModal: "./pokemonPictures/Pyroar.png",
            background: "redGradient",
        },
        id3: {
            name: "Pikachu",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Pikachu.png",
            imageUrlModal: "./pokemonPictures/Pikachu.png",
            background: "yellowGradient",
        },
        id4: {
            name: "Quilava",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Quilava.png",
            imageUrlModal: "./pokemonPictures/Quilava.png",
            background: "greenGradient",
        },
        id5: {
            name: "Squirtle",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Squirtle.png",
            imageUrlModal: "/pokemonPictures/Squirtle.png",
            background: "blueGradient",
        },
        id6: {
            name: "Charizard",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Charizard.png",
            imageUrlModal: "./pokemonPictures/CharizardModal.png",
            background: "redGradient",
        },
        id7: {
            name: "Mudkip",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Mudkip.png",
            imageUrlModal: "./pokemonPictures/Mudkip.png",
            background: "blueGradient",
        },
        id8: {
            name: "Jigglypuff",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Jigglypuff.png",
            imageUrlModal: "./pokemonPictures/Jigglypuff.png",
            background: "pinkGradient",
        },
        id9: {
            name: "Tyranitar",
            attack: 419,
            defence: 49,
            type1: "Grass",
            type2: "Poison",
            imageUrl: "./pokemonPictures/Tyranitar.png",
            imageUrlModal: "./pokemonPictures/Tyranitar.png",
            background: "greenGradient",
        },
    });
});

module.exports = router;
